# Generated by Django 3.2.2 on 2021-06-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategoriya', 'verbose_name_plural': 'kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-vaqt'], 'verbose_name': 'yangilik', 'verbose_name_plural': 'yangiliklar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='vaqt',
            field=models.DateField(auto_now_add=True, verbose_name='vaqti'),
        ),
    ]
