# Generated by Django 3.2.4 on 2021-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0002_auto_20210613_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='vaqt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vaqti'),
        ),
    ]
