# Generated by Django 3.2.4 on 2021-08-14 21:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0003_alter_news_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tekst',
            field=ckeditor.fields.RichTextField(verbose_name='matni'),
        ),
    ]
